name: Sync to Railway Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Debug token presence
        run: |
          if [ -z "${{ secrets.TARGET_REPO_TOKEN }}" ]; then
            echo "TOKEN IS EMPTY ❌"
            exit 1
          else
            echo "TOKEN EXISTS ✅"
          fi

      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Push to Repo B
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "sync@github.com"

          git remote add target https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/exorcist073-svg/seal.git
          
          git push target main --force